# Generated by Django 6.0.1 on 2026-02-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nick', models.CharField(max_length=25, unique=True)),
                ('cargo', models.CharField(default='nulo', max_length=50)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('arts', models.IntegerField(default=0)),
                ('real_name', models.CharField(default='', max_length=255, null=True)),
                ('bio', models.CharField(default='', max_length=255, null=True)),
                ('art_style', models.CharField(choices=[('', 'selecione um estilo'), ('música clássica', 'música clássica'), ('jazz', 'jazz'), ('blues', 'blues'), ('gospel', 'gospel'), ('soul', 'soul'), ('pop', 'pop'), ('rock', 'rock'), ('country', 'country'), ('desenho2d', 'desenho 2d'), ('realismo', 'realismo'), ('cartoon', 'cartoon'), ('manga', 'mangá'), ('chibi', 'chibi'), ('caricatura', 'caricatura'), ('doodleart', 'doodleart'), ('surrealismo', 'surrealismo'), ('modelagem3d', 'modelagem 3d'), ('videomaker', 'videomaker'), ('editordevideo', 'editor de vídeos'), ('filmmaker', 'filmmaker'), ('roteirista', 'roteirista'), ('designergrafico', 'designer gráfico'), ('editorfotos', 'editor de fotos'), ('colorista', 'colorista'), ('motiondesigner', 'motiondesigner')], default='', max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='base64image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.TextField(null=True)),
            ],
        ),
    ]
