# Generated by Django 6.0.1 on 2026-02-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_base64image_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='base64image',
            new_name='post',
        ),
    ]
