# Generated by Django 6.0.1 on 2026-02-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_base64image_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
