# Generated by Django 6.0.1 on 2026-02-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='core_picture',
            field=models.TextField(default='', null=True),
        ),
    ]
