# Generated by Django 6.0.1 on 2026-03-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_nick_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
