# Generated by Django 6.0.1 on 2026-01-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
