# Generated by Django 6.0.1 on 2026-01-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
