# Generated by Django 6.0.1 on 2026-01-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.TextField(default='nulo', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.TextField(max_length=25, unique=True),
        ),
    ]
