# Generated by Django 6.0.1 on 2026-01-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0007_user_cargo_alter_user_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='art_type',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
