# Generated by Django 6.0.1 on 2026-01-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0009_alter_user_email_alter_user_nick_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='art_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_user',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(default='nulo', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
