# Generated by Django 6.0.1 on 2026-01-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0011_remove_user_id_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
