# Generated by Django 6.0.1 on 2026-01-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0013_user_bio_user_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
