# Generated by Django 6.0.1 on 2026-02-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0016_alter_user_bio_alter_user_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='art_style',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
