# Generated by Django 6.0.1 on 2026-02-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0018_alter_user_art_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='art_style',
            field=models.CharField(choices=[('classic', 'música clássica'), ('jazz', 'jazz'), ('blues', 'blues'), ('gospel', 'gospel'), ('soul', 'soul'), ('pop', 'pop'), ('rock', 'rock'), ('country', 'country'), ('desenho2d', 'desenho 2d'), ('realismo', 'realismo'), ('cartoon', 'cartoon'), ('manga', 'mangá'), ('chibi', 'chibi'), ('caricatura', 'caricatura'), ('doodleart', 'doodleart'), ('surrealismo', 'surrealismo'), ('modelagem3d', 'modelagem 3d'), ('videomaker', 'videomaker'), ('editordevideo', 'editor de vídeos'), ('filmmaker', 'filmmaker'), ('roteirista', 'roteirista'), ('designergrafico', 'designer gráfico'), ('editorfotos', 'editor de fotos'), ('colorista', 'colorista'), ('motiondesigner', 'motiondesigner')], default='', max_length=50, null=True),
        ),
    ]
