# Generated by Django 6.0.1 on 2026-02-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0021_alter_user_art_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='base64image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('image', models.TextField()),
            ],
        ),
    ]
