# Generated by Django 6.0.1 on 2026-02-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0022_base64image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base64image',
            name='image',
        ),
    ]
