# Generated by Django 6.0.1 on 2026-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0024_remove_base64image_image_remove_base64image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='base64image',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
