# Generated by Django 5.2.14 on 2026-06-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='link',
            new_name='url',
        ),
    ]
