# Generated by Django 5.2.12 on 2026-03-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
