# Generated by Django 5.2.12 on 2026-03-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_followers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='user',
            new_name='seguido',
        ),
        migrations.AddField(
            model_name='user',
            name='last_nick_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
