# Generated by Django 5.2.12 on 2026-03-29 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_user_followers_seguido_user_last_nick_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='seguido',
            new_name='user',
        ),
    ]
