# Generated by Django 5.2.12 on 2026-03-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='interests',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
