# Generated by Django 5.2.12 on 2026-03-31 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_interests_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interests',
            old_name='interests',
            new_name='interest',
        ),
    ]
