# Generated by Django 6.0.1 on 2026-02-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='data_post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post_owner_user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
