# Generated by Django 6.0.1 on 2026-02-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_likes_post_id_alter_likes_user_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post_id',
            new_name='post',
        ),
    ]
