# Generated by Django 6.0.1 on 2026-02-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_rename_post_id_likes_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post',
            new_name='post_l',
        ),
    ]
