# Generated by Django 6.0.1 on 2026-02-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_rename_post_l_likes_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='nol',
            field=models.IntegerField(default=0),
        ),
    ]
