# Generated by Django 6.0.1 on 2026-02-21 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_likes_nol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='nol',
        ),
    ]
