# Generated by Django 6.0.1 on 2026-02-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_remove_likes_nol'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
