# Generated by Django 6.0.1 on 2026-02-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post_id',
            new_name='post',
        ),
    ]
