# Generated by Django 6.0.1 on 2026-02-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
