# Generated by Django 5.2.12 on 2026-04-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='like_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='share',
            field=models.BooleanField(default=True),
        ),
    ]
