# Generated by Django 5.2.12 on 2026-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_comment_post_like_number_post_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
