# Generated by Django 5.2.13 on 2026-05-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='roxotags',
            field=models.TextField(null=True),
        ),
    ]
