# Generated by Django 6.0.1 on 2026-02-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_rename_post_likes_post_l'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post_l',
            new_name='post_id',
        ),
    ]
