# Generated by Django 5.2.13 on 2026-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='base64',
        ),
        migrations.AddField(
            model_name='media',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
