# Generated by Django 5.2.13 on 2026-08-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_remove_media_base64_media_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('audio', 'Áudio')], default='image', max_length=10),
        ),
    ]
