# Generated by Django 5.2.13 on 2026-08-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_media_duration_seconds_media_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='duration_seconds',
        ),
    ]
