# Generated by Django 5.2.13 on 2026-08-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_remove_media_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_url',
        ),
    ]
